-- DROP DATABASE  BD_LOCADORA;
CREATE DATABASE  BD_LOCADORA;
USE BD_LOCADORA;

CREATE TABLE CLIENTE(
ID_CLIENTE  INT PRIMARY KEY AUTO_INCREMENT,
NOME      VARCHAR(100) NOT NULL,
IDADE INT  NOT NULL,
RUA  VARCHAR(100),
NUMERO VARCHAR(10),
COMPLEMENTO VARCHAR(120),
CEP   VARCHAR(8) NOT NULL,
TELEFONE VARCHAR(20),
CELULAR  VARCHAR(20) NOT NULL,
RG     VARCHAR(9) UNIQUE NOT NULL,
CPF    VARCHAR(11)UNIQUE  NOT NULL,
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ATUALIZACAO DATETIME DEFAULT NOW(),
ID_USUARIO  INT NOT NULL,
CONSTRAINT CK_CEP CHECK(LENGTH(CEP)= 8) ,
CONSTRAINT CK_RG CHECK(LENGTH(RG)= 9) ,
CONSTRAINT CK_CPF CHECK(LENGTH(CPF) = 11),
CONSTRAINT CK_CELULAR CHECK(INSTR(CELULAR,'9') = 1)
);

CREATE TABLE FUNCIONARIO(
ID_FUNC INT AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
DATA_NAS DATE NOT NULL,
IDADE INT,
SEXO CHAR DEFAULT 'M',
RG VARCHAR(9) UNIQUE NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
TELEFONE VARCHAR(20),
CELULAR VARCHAR(20),
RUA VARCHAR(100)NOT NULL,
NUMERO VARCHAR(10)NOT NULL,
COMPLEMENTO VARCHAR(120),
CEP VARCHAR(8) NOT NULL,
VT VARCHAR(1) DEFAULT 'Y',
VALOR_PAGO_VT DECIMAL(9,2),
VALOR_PAGO_INSS DECIMAL(9,2),
QTDE_DIAS    INT DEFAULT 6,
HORARIO_ENTRADA TIME DEFAULT '09:00:00',
HORARIO_SAIDA   TIME DEFAULT '18:00:00',
SALARIO_BRUTO  DECIMAL(9,2) DEFAULT 500.00,
SALARIO_LIQUIDO DECIMAL(9,2),
CARGA_HORARIA_DIARIA INT,
CARGA_HORARIA_SEMANAL INT,
CARGA_HORARIA_MENSAL INT,
CARGO  VARCHAR(50) DEFAULT 'ATENDENTE',
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ATUALIZACAO DATETIME DEFAULT NOW(),
ID_USUARIO  INT NOT NULL,
CONSTRAINT PK_ID_FUNC PRIMARY KEY (ID_FUNC),
CONSTRAINT CK_SEXO CHECK(SEXO IN('M','F')),
CONSTRAINT CK_VT CHECK (VT IN('Y','N')),
CONSTRAINT CK_IDADE CHECK(IDADE >= 17 AND IDADE <= 60) ,
CONSTRAINT CK_RG_FUNC    CHECK(LENGTH(RG)  = 9 ),
CONSTRAINT CK_CPF_FUNC   CHECK(LENGTH(CPF) = 11) ,
CONSTRAINT CK_CELULAR_FUNC CHECK(INSTR(CELULAR,'9') = 1),
CONSTRAINT CK_CEP_FUNC   CHECK(LENGTH(CEP)= 8) ,
CONSTRAINT CK_QTDE_DIAS CHECK(QTDE_DIAS >= 1 AND QTDE_DIAS <= 6),
CONSTRAINT CK_SALARIO CHECK(SALARIO >= 500) 
);

CREATE TABLE LOGIN(
ID_LOGIN INT AUTO_INCREMENT,
ID_FUNC   INT UNIQUE NOT NULL,
SENHA VARCHAR(20) NOT NULL,
PERGUNTA VARCHAR(50) NOT NULL,
RESPOSTA VARCHAR(50) NOT NULL,
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ATUALIZACAO DATETIME DEFAULT NOW(),
ID_USUARIO  INT NOT NULL,
CONSTRAINT PK_ID_LOGIN PRIMARY KEY(ID_LOGIN),
CONSTRAINT FK_ID_FUNC_LOGIN FOREIGN KEY(ID_FUNC) REFERENCES FUNCIONARIO(ID_FUNC),
CONSTRAINT CK_SENHA CHECK(LENGTH(SENHA) >= 6)
);

CREATE TABLE DVD_JOGO(
ID_DVD_JOGO INT AUTO_INCREMENT,
NOME VARCHAR(250)UNIQUE NOT NULL,
GENERO VARCHAR(100),
CLASSIFICACAO_IDADE INT NOT NULL,
TIPO VARCHAR(40),
PRECO DECIMAL(9,2) NOT NULL,
DATA_FABRICACAO DATETIME,
DATA_CADASTRO DATETIME DEFAULT NOW(),
QTDE INT DEFAULT 1,
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ATUALIZACAO DATETIME DEFAULT NOW(),
ID_USUARIO  INT NOT NULL,
CONSTRAINT PK_ID_DVD_JOGO PRIMARY KEY (ID_DVD_JOGO),
CONSTRAINT CK_PRECO_FILME CHECK(PRECO > 0),
CONSTRAINT CK_QTDE CHECK (QTDE >= 1)
);

CREATE TABLE EMPRESTIMO_DVD_JOGO(
ID_EMP_DVD_JOGO INT AUTO_INCREMENT,
QTDE_DIAS_EMPR INT NOT NULL,
VALOR_DIARIA DECIMAL(9,2) NOT NULL,
VALOR_TOTAL  DECIMAL(9,2),
ID_FUNC INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_DVD_JOGO INT NOT NULL,
QTDE_EMPRESTADO INT NOT NULL DEFAULT 1,
DATA_EMPRESTIMO DATETIME DEFAULT NOW(),
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ATUALIZACAO DATETIME DEFAULT NOW(),
ID_USUARIO  INT NOT NULL,
CONSTRAINT PK_ID_DVD_JOGO_ID_CLIENTE PRIMARY KEY(ID_EMP_DVD_JOGO,ID_DVD_JOGO,ID_CLIENTE),
CONSTRAINT CK_QTDE_DIAS_EMPR  CHECK(QTDE_DIAS_EMPR > 0),
CONSTRAINT CK_VALOR_DIARIA    CHECK(VALOR_DIARIA > 0) ,
CONSTRAINT FK_ID_FUNC_EMP     FOREIGN KEY(ID_FUNC)REFERENCES FUNCIONARIO(ID_FUNC),
CONSTRAINT FK_ID_CLIENTE      FOREIGN KEY(ID_CLIENTE)REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT FK_ID_DVD_JOGO     FOREIGN KEY(ID_DVD_JOGO)REFERENCES DVD_JOGO(ID_DVD_JOGO),
CONSTRAINT CK_QTDE_ALUGADA    CHECK(QTDE_EMPRESTADO >= 1)
);

CREATE TABLE HISTORICO_EMPRESTIMO_DVD_JOGO(
ID_EMP_DVD_JOGO INT,
ID_FUNC INT,
NOME_FUNCIONARIO VARCHAR(150) ,
ID_CLIENTE INT,
NOME_CLIENTE VARCHAR(150),
ID_DVD_JOGO INT ,
NOME_DVD_JOGO VARCHAR(200),
QTDE_EMPRESTADO INT,
QTDE_DIAS_EMPR INT,
VALOR_DIARIA DECIMAL(9,2),
VALOR_TOTAL  DECIMAL(9,2),
DATA_EMPRESTIMO DATETIME DEFAULT NOW(),
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ATUALIZACAO DATETIME DEFAULT NOW(),
ID_USUARIO  INT NOT NULL
);

CREATE OR REPLACE VIEW HISTORICO_EMPRESTIMO_DVD_JOGO_V AS 
SELECT  ID_EMP_DVD_JOGO,
		ID_FUNC,
		NOME_FUNCIONARIO,
		ID_CLIENTE,
		NOME_CLIENTE,
		ID_DVD_JOGO,
		NOME_DVD_JOGO,
		QTDE_EMPRESTADO,
		QTDE_DIAS_EMPR,
		VALOR_DIARIA,
		VALOR_TOTAL,
		date_format(DATA_EMPRESTIMO,'%d/%m/%Y')DATA_EMPRESTIMO,
        date_format(DATE_ADD(DATA_EMPRESTIMO, INTERVAL QTDE_DIAS_EMPR DAY),'%d/%m/%Y') DATA_DEVOLUCAO,
		date_format(DATA_CRIACAO,'%d/%m/%Y %H:%i:%s')DATA_CRIACAO,
		date_format(DATA_ATUALIZACAO,'%d/%m/%Y %H:%i:%s')DATA_ATUALIZACAO,ID_USUARIO
FROM HISTORICO_EMPRESTIMO_DVD_JOGO
ORDER BY DATA_EMPRESTIMO, QTDE_DIAS_EMPR ;


-- VERIFICANDO OS CAMPOS DA TABELA CLIENTE
SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE WHERE NOME LIKE '%A%';

delete from cliente where id_cliente in (7);
commit;

-- INSERT DE MANEIRA TRADICIONAL
INSERT INTO CLIENTE(ID_CLIENTE,NOME,IDADE,RUA,NUMERO,COMPLEMENTO,CEP,TELEFONE,CELULAR,RG,CPF)
VALUES(1,'CARLOS HENRIQUE DE SOUZA',26,'ARNALDO DE SOUZA GOMES',23,'BLOCO 19 APT: 60','56778900','012312000','987671239','098765432','09876543211');
-- CONFIRMANDO TODAS AS ALTERACOES E INSERCOES AO SERVIDOR PARA NAO PERDER AS TRANSACOES
COMMIT;

-- VERIFICANDO SE O REGISTRO FOI INSERIDO
SELECT * FROM CLIENTE;

INSERT INTO CLIENTE(ID_CLIENTE,NOME,IDADE,RUA,NUMERO,CEP,CELULAR,RG,CPF)
VALUES(2,'LETICIA VIERA DA SILVA',22,'MARIA DE MENDES',133,'04877121','987880987','098765431','09876543212');

-- CONFIRMANDO AS ALTERACOES E INSERCOES AO SERVIDOR
COMMIT;

-- VERIFICANDO AS COLUNAS DA TABELA DE FUNCIONARIO
SELECT * FROM FUNCIONARIO;

# DELETE FROM FUNCIONARIO WHERE ID_FUNC = 1;

INSERT INTO FUNCIONARIO VALUES(1,'MIGUEL DA SILVA ALVEZ','1992/06/18', 27,'M','912345678',
'12345567890',NULL,NULL,'PASCOAL BURNGEU ',1091,NULL,'04210121',DEFAULT,DEFAULT,DEFAULT,'1028.00');

INSERT INTO FUNCIONARIO(NOME,DATA_NAS,IDADE,SEXO,RG,CPF,RUA,NUMERO,CEP,CARGO) 
	VALUES('ADMIN SYSTEM','2019-09-01',1,'F','000000000','00000000000',
           'RUA: ALAMEDA DOS ANJOS','231','04138098','ADMINISTRADOR DE SISTEMA');


-- VERIFICANDO O INSERT
SELECT * FROM FUNCIONARIO;

-- CONFIRMANDO O INSERT
COMMIT;

-- INSERT DA 3 FORMA

-- VERIFICANDO A TABELA DE DVDS E JOGOS
SELECT * FROM DVD_JOGO;

-- INSERT ATRAVES  DE VARIAVEIS CRIADAS 
INSERT INTO DVD_JOGO(ID_DVD_JOGO,NOME,GENERO,CLASSIFICACAO_IDADE,TIPO,PRECO,DATA_FABRICACAO,QTDE) 
              VALUES(1,'Fifa 2019 ','Esporte',10,'Esporte',250.00,'02-06-2017', 2);

COMMIT;

INSERT INTO DVD_JOGO(ID_DVD_JOGO,NOME,GENERO,CLASSIFICACAO_IDADE,TIPO,PRECO,DATA_FABRICACAO,QTDE) 
              VALUES(2,'MARIO KART DE NINTENDO SWITCH','CORRIDA',10,'JOGO',250.00,'19/02/2017',5);
COMMIT;

-- VERIFICANDO SE AMBOS OS REGISTROS FORAM INSERIDOS
SELECT * FROM DVD_JOGO;

-- INSERINDO 4 FORMA MAS ANTES VAMOS ADD MAIS UM REGISTRO

-- VERIFICANDO A TABELA DE EMPRESTIMO
SELECT * FROM EMPRESTIMO_DVD_JOGO;

INSERT INTO EMPRESTIMO_DVD_JOGO VALUES(1,3,2.50,7.50,1,1,1,1);

-- CONFIRMANDO O INSERT
COMMIT;

-- VERIFICANDO O REGISTRO INSERIDO
SELECT * FROM EMPRESTIMO_DVD_JOGO;

-- INSERINDO ATRAVES DO RESULTADO DE UM SELECT
INSERT INTO EMPRESTIMO_DVD_JOGO
SELECT 2,QTDE_DIAS_EMPR,VALOR_DIARIA,
       VALOR_TOTAL,ID_FUNC,ID_CLIENTE,ID_DVD_JOGO,QTDE_EMPRESTADO
 FROM EMPRESTIMO_DVD_JOGO
 WHERE ID_EMP_DVD_JOGO = 1;
 

SELECT ID_DVD_JOGO FROM DVD_JOGO WHERE UPPER(NOME) = 'Fifa 2019';


--  VIEW DE CLIENTES
CREATE OR REPLACE VIEW CLIENTES_CADASTRADOS AS
SELECT ID_CLIENTE,NOME,IDADE,RUA,NUMERO,COMPLEMENTO,CEP,TELEFONE,
	   CELULAR,RG,CPF,date_format(DATA_CRIACAO, '%d/%m/%Y %H:%i:%s')DATA_CRIACAO,
       date_format(DATA_ATUALIZACAO, '%d/%m/%Y %H:%i:%s')DATA_ATUALIZACAO ,ID_USUARIO 
FROM  CLIENTE;

-- VIEW DE FUNCIONARIO
CREATE OR REPLACE VIEW FUNCIONARIOS_CADASTRADOS AS 
SELECT ID_FUNC,
       NOME,
       date_format(DATA_NAS,'%d/%m/%Y')DATA_NASCIMENTO,
       IDADE,
       SEXO,
       RG,
	   CPF,TELEFONE,CELULAR,RUA,NUMERO,COMPLEMENTO,CEP,
       QTDE_DIAS,DATE_FORMAT(HORARIO_ENTRADA,'%H:%i:%s')HORARIO_ENTRADA,
       DATE_FORMAT(HORARIO_SAIDA,'%H:%i:%s')HORARIO_SAIDA,
       CARGO,
       VALOR_PAGO_VT,
       VALOR_PAGO_INSS,
       SALARIO_BRUTO,
       SALARIO_LIQUIDO,
       CARGA_HORARIA_DIARIA,
       CARGA_HORARIA_SEMANAL,
       CARGA_HORARIA_MENSAL,
	   date_format(DATA_CRIACAO,'%d/%m/%Y %H:%i:%s')DATA_CRIACAO,
       date_format(DATA_ATUALIZACAO,'%d/%m/%Y %H:%i:%s')DATA_ATUALIZACAO
       ,ID_USUARIO
 FROM FUNCIONARIO;

SELECT * FROM FUNCIONARIOS_CADASTRADOS;

-- VIEW DE  DVD E JOGOS 
CREATE OR REPLACE VIEW DVD_JOGOS_V AS
SELECT ID_DVD_JOGO,NOME,GENERO,
       CASE 
         WHEN CLASSIFICACAO_IDADE = 0 THEN 
               "Livre para todos os Públicos"
		 ELSE 
           CLASSIFICACAO_IDADE
	   END CLASSIFICACAO_IDADE,
       TIPO,
       PRECO,DATE_FORMAT(DATA_FABRICACAO,'%d/%m/%Y')DATA_FABRICACAO,
       DATE_FORMAT(DATA_CADASTRO,'%d/%m/%Y %H:%i:%s')DATA_CADASTRO,
       QTDE,
       DATE_FORMAT(DATA_CRIACAO,'%d/%m/%Y %H:%i:%s')DATA_CRIACAO,
       DATE_FORMAT(DATA_ATUALIZACAO,'%d/%m/%Y %H:%i:%s')DATA_ATUALIZACAO,
       ID_USUARIO
 FROM DVD_JOGO;
 --
CREATE OR REPLACE VIEW LOGINS_V AS
 SELECT L.ID_LOGIN,
        F.ID_FUNC,
        F.NOME NOME_FUNCIONARIO,
        F.CPF,
        L.SENHA,
        L.PERGUNTA,
        L.RESPOSTA,
        DATE_FORMAT(L.DATA_CRIACAO ,'%d/%m/%Y') DATA_CRIACAO, 
        DATE_FORMAT(L.DATA_CRIACAO ,'%d/%m/%Y') DATA_ATUALIZACAO
FROM LOGIN L,
     FUNCIONARIO F
WHERE 1 = 1
 AND L.ID_FUNC = F.ID_FUNC;
 
 SELECT * FROM LOGINS_V;
 SELECT * FROM LOGIN;
 --
 SELECT * FROM DVD_JOGOS_V;
-- VIEW DE ALUGUEL DE GAMES E DVDS
CREATE OR REPLACE VIEW DVD_JOGOS_ALUGADO_V AS
SELECT EDJ.ID_EMP_DVD_JOGO,
      (SELECT DJ.NOME 
         FROM DVD_JOGO DJ
         WHERE 1= 1
          AND DJ.ID_DVD_JOGO = EDJ.ID_DVD_JOGO) NOME_DVD_JOGO,
	  (SELECT C.NOME
        FROM CLIENTE C
        WHERE 1 = 1
         AND C.ID_CLIENTE = EDJ.ID_CLIENTE) NOME_CLIENTE,
	  EDJ.QTDE_DIAS_EMPR,
      EDJ.VALOR_DIARIA,
      EDJ.VALOR_TOTAL,EDJ.QTDE_EMPRESTADO,
      date_format(EDJ.DATA_EMPRESTIMO, '%d/%m/%Y')DATA_EMPRESTIMO,
      date_format(DATE_ADD(DATA_EMPRESTIMO, INTERVAL QTDE_DIAS_EMPR DAY),'%d/%m/%Y') DATA_DEVOLUCAO,
      date_format(EDJ.DATA_CRIACAO, '%d/%m/%Y')DATA_CRIACAO,
      date_format(EDJ.DATA_ATUALIZACAO, '%d/%m/%Y')DATA_ATUALIZACAO,ID_USUARIO
 FROM EMPRESTIMO_DVD_JOGO EDJ;
 
-- ALTER TABLE EMPRESTIMO_DVD_JOGO DROP COLUMN DATA_DEVOLUCAO DATE NOW();
SELECT * FROM DVD_JOGOS_ALUGADO_V;

DELETE FROM LOGIN WHERE ID_LOGIN = 2;
COMMIT;
SELECT * FROM LOGIN;

-- ----------------------------------------------------------------------------
/* 
ALTER TABLE FUNCIONARIO ADD VT VARCHAR(1) DEFAULT 'Y';
ALTER TABLE FUNCIONARIO ADD CONSTRAINT CK_VT CHECK (VT IN('Y','N'));
ALTER TABLE FUNCIONARIO CHANGE VALOR_VT VALOR_PAGO_VT DECIMAL(9,2);
ALTER TABLE FUNCIONARIO CHANGE INSS VALOR_PAGO_INSS DECIMAL(9,2);
ALTER TABLE FUNCIONARIO ADD SALARIO_LIQUIDO DECIMAL(9,2);
ALTER TABLE FUNCIONARIO ADD CARGA_HORARIA_DIARIA INT;
ALTER TABLE FUNCIONARIO ADD CARGA_HORARIA_SEMANAL INT;
ALTER TABLE FUNCIONARIO ADD CARGA_HORARIA_MENSAL INT;
ALTER TABLE FUNCIONARIO CHANGE SALARIO SALARIO_BRUTO DECIMAL(9,2) DEFAULT 500.00; 
ALTER TABLE CLIENTE                 MODIFY ID_USUARIO  INT NOT NULL;
ALTER TABLE FUNCIONARIO             MODIFY ID_USUARIO  INT NOT NULL;
ALTER TABLE DVD_JOGO                MODIFY ID_USUARIO  INT NOT NULL;
ALTER TABLE LOGIN                   MODIFY ID_USUARIO  INT NOT NULL;
ALTER TABLE EMPRESTIMO_DVD_JOGO     MODIFY ID_USUARIO  INT NOT NULL;
ALTER TABLE HISTORICO_EMPRESTIMO_DVD_JOGO MODIFY ID_USUARIO  INT NOT NULL;*/
-- VT,INSS,SALARIO LIQUIDO, CARGA HORARIA,SEMANAL E MENSAL

/* INSERT INTO HISTORICO_EMPRESTIMO_DVD_JOGO
SELECT EDJ.ID_EMP_DVD_JOGO,EDJ.ID_FUNC,(SELECT F.NOME 
									     FROM FUNCIONARIO F
									     WHERE F.ID_FUNC = EDJ.ID_FUNC)NOME_FUNCIONARIO,
EDJ.ID_CLIENTE,(SELECT C.NOME 
				FROM CLIENTE C
				WHERE C.ID_CLIENTE = EDJ.ID_CLIENTE)NOME_CLIENTE,
EDJ.ID_DVD_JOGO,(SELECT DJ.NOME
                   FROM DVD_JOGO DJ
				   WHERE DJ.ID_DVD_JOGO = EDJ.ID_DVD_JOGO)NOME_DVD_JOGO, 
EDJ.QTDE_EMPRESTADO,EDJ.QTDE_DIAS_EMPR, EDJ.VALOR_DIARIA, EDJ.VALOR_TOTAL,
EDJ.DATA_EMPRESTIMO, EDJ.DATA_CRIACAO, EDJ.DATA_ATUALIZACAO 
FROM EMPRESTIMO_DVD_JOGO EDJ; */

SELECT * FROM FUNCIONARIO;
SELECT * FROM CLIENTE;
SELECT * FROM DVD_JOGO;
SELECT * FROM DVD_JOGOS_ALUGADO_V;
SELECT * FROM EMPRESTIMO_DVD_JOGO;
SELECT * FROM HISTORICO_EMPRESTIMO_DVD_JOGO;
SELECT * FROM HISTORICO_EMPRESTIMO_DVD_JOGO_V;
SELECT * FROM LOGINS_V;

DELETE FROM DVD_JOGO WHERE ID_DVD_JOGO BETWEEN 109 AND 4015; 
COMMIT; 



