DROP FUNCTION RETORNA_CARGO_F ;

DELIMITER $$;
CREATE FUNCTION RETORNA_CARGO_F(P_ID_FUNC INT) RETURNS VARCHAR(100)

BEGIN
   
   DECLARE LV_CARGO VARCHAR(100) ;
   
   SELECT UPPER(CARGO) CARGO
    INTO LV_CARGO
	FROM FUNCIONARIO
	WHERE ID_FUNC = P_ID_FUNC;
   
   RETURN LV_CARGO;
   
END $$;

SELECT RETORNA_CARGO_F(6) CARGO;