-- CRIANDO UMA TRIGGER PARA CALCULAR O VALOR DE VT,INSS,SALARIO LIQUIDO, CARGA HORARIA,SEMANAL E MENSAL
DROP TRIGGER  CALCULA_DADOS_FUNCIONARIO_TG;
DELIMITER $$;
CREATE TRIGGER CALCULA_DADOS_FUNCIONARIO_TG
BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW

BEGIN
  --
   -- CALCULANDO A IDADE DO FUNCIONARIO
  DECLARE LN_IDADE INT;
  SET LN_IDADE =  CAST(SUBSTR(CURDATE(), 1, 4)AS DECIMAL(4)) - CAST(SUBSTR(NEW.DATA_NAS, 1, 4)AS DECIMAL(4)); 
  SET NEW.IDADE = LN_IDADE;
  -- CALCULANDO O VT
   IF NEW.VT = 'Y' THEN
   --
	SET NEW.VALOR_PAGO_VT = (NEW.SALARIO_BRUTO/100) * 6;
   END IF;
   
   -- CALCULANDO O INSS
   IF NEW.SALARIO_BRUTO >= 900 AND NEW.SALARIO_BRUTO <= 1693.72 THEN
      SET NEW.VALOR_PAGO_INSS  = (NEW.SALARIO_BRUTO/100) * 8;
   END IF;

   IF NEW.SALARIO_BRUTO >= 1693.73 AND NEW.SALARIO_BRUTO <= 2822.90 THEN
      SET NEW.VALOR_PAGO_INSS  = (NEW.SALARIO_BRUTO/100) * 9;
   END IF;
   
   IF NEW.SALARIO_BRUTO >= 2822.91 AND NEW.SALARIO_BRUTO <= 5645.80 THEN
      SET NEW.VALOR_PAGO_INSS  = (NEW.SALARIO_BRUTO/100) * 11;
   END IF;
   
   IF NEW.SALARIO_BRUTO > 5645.80 THEN
     SET NEW.VALOR_PAGO_INSS   = 625.00;
   END IF;
   -- # SALARIO LIQUIDO
   IF NEW.VT = 'Y' THEN
     SET NEW.SALARIO_LIQUIDO = NEW.SALARIO_BRUTO -(NEW.VALOR_PAGO_VT+ NEW.VALOR_PAGO_INSS);
   ELSE
      SET NEW.SALARIO_LIQUIDO = NEW.SALARIO_BRUTO - NEW.VALOR_PAGO_INSS;
      SET NEW.VALOR_PAGO_VT = 0;
   END IF;
   
   IF NEW.SALARIO_BRUTO < 600.00 THEN
      SET NEW.SALARIO_LIQUIDO = NEW.SALARIO_BRUTO;
      SET NEW.VALOR_PAGO_INSS = 0;
   END IF;

   -- #CALCULANDO QTDE DE HORAS DIARIA
   SET NEW.CARGA_HORARIA_DIARIA = (DATE_FORMAT(DATE_SUB(NEW.HORARIO_SAIDA,INTERVAL NEW.HORARIO_ENTRADA 
													 HOUR_SECOND), '%h'));
   
   -- # CALCULANDO QTDE DE CARGA HORARIO SEMANAL
	 SET NEW.CARGA_HORARIA_SEMANAL =  NEW.CARGA_HORARIA_DIARIA * NEW.QTDE_DIAS;
   
   -- # CALCULANDO QTDE DE CARGA HORARIO MENSAL
     IF NEW.QTDE_DIAS = 5 THEN
       SET NEW.CARGA_HORARIA_MENSAL  =  NEW.CARGA_HORARIA_SEMANAL  * 22;
     END IF;
     
     IF NEW.QTDE_DIAS = 6 THEN
       SET NEW.CARGA_HORARIA_MENSAL  :=  NEW.CARGA_HORARIA_SEMANAL  * 26;
     END IF;
   
END$$;
-- ---------------------------------------------------------------------------------------
-- CRIANDO UMA TRIGGER PARA CALCULAR O VALOR DE VT,INSS,SALARIO LIQUIDO, CARGA HORARIA,SEMANAL E MENSAL
DROP TRIGGER CALCULA_DADOS_FUNCIONARIO_UPD_TG;
DELIMITER $$;
CREATE TRIGGER CALCULA_DADOS_FUNCIONARIO_UPD_TG
BEFORE UPDATE ON FUNCIONARIO
FOR EACH ROW

BEGIN
  --
  -- CALCULANDO A IDADE DO FUNCIONARIO
  DECLARE LN_IDADE INT;
  SET LN_IDADE =  CAST(SUBSTR(CURDATE(), 1, 4)AS DECIMAL(4)) - CAST(SUBSTR(NEW.DATA_NAS, 1, 4)AS DECIMAL(4)); 
  SET NEW.IDADE = LN_IDADE;
  
  -- CALCULANDO O VT
   IF NEW.VT = 'Y' THEN
   --
	SET NEW.VALOR_PAGO_VT = (NEW.SALARIO_BRUTO/100) * 6;
   END IF;
   
   -- CALCULANDO O INSS
   IF NEW.SALARIO_BRUTO >= 900 AND NEW.SALARIO_BRUTO <= 1693.72 THEN
      SET NEW.VALOR_PAGO_INSS  = (NEW.SALARIO_BRUTO/100) * 8;
   END IF;

   IF NEW.SALARIO_BRUTO >= 1693.73 AND NEW.SALARIO_BRUTO <= 2822.90 THEN
      SET NEW.VALOR_PAGO_INSS  = (NEW.SALARIO_BRUTO/100) * 9;
   END IF;
   
   IF NEW.SALARIO_BRUTO >= 2822.91 AND NEW.SALARIO_BRUTO <= 5645.80 THEN
      SET NEW.VALOR_PAGO_INSS  = (NEW.SALARIO_BRUTO/100) * 11;
   END IF;
   
   IF NEW.SALARIO_BRUTO > 5645.80 THEN
     SET NEW.VALOR_PAGO_INSS   = 625.00;
   END IF;
   -- # SALARIO LIQUIDO
   IF NEW.VT = 'Y' THEN
     SET NEW.SALARIO_LIQUIDO = NEW.SALARIO_BRUTO -(NEW.VALOR_PAGO_VT+ NEW.VALOR_PAGO_INSS);
   ELSE
      SET NEW.SALARIO_LIQUIDO = NEW.SALARIO_BRUTO - NEW.VALOR_PAGO_INSS;
      SET NEW.VALOR_PAGO_VT = 0;
   END IF;
   
   IF NEW.SALARIO_BRUTO < 600.00 THEN
      SET NEW.SALARIO_LIQUIDO = NEW.SALARIO_BRUTO;
      SET NEW.VALOR_PAGO_INSS = 0;
   END IF;

   -- #CALCULANDO QTDE DE HORAS DIARIA
   IF NEW.HORARIO_ENTRADA <> OLD.HORARIO_ENTRADA OR NEW.HORARIO_SAIDA <> OLD.HORARIO_SAIDA THEN
	   SET NEW.CARGA_HORARIA_DIARIA = (DATE_FORMAT(DATE_SUB(NEW.HORARIO_SAIDA,INTERVAL NEW.HORARIO_ENTRADA 
													 HOUR_SECOND), '%h'));
   END IF;
     
   -- # CALCULANDO QTDE DE CARGA HORARIO SEMANAL
	 SET NEW.CARGA_HORARIA_SEMANAL =  NEW.CARGA_HORARIA_DIARIA * NEW.QTDE_DIAS;
   
   -- # CALCULANDO QTDE DE CARGA HORARIO MENSAL
     IF NEW.QTDE_DIAS = 5 THEN
       SET NEW.CARGA_HORARIA_MENSAL  =  NEW.CARGA_HORARIA_SEMANAL  * 22;
     END IF;
     
     IF NEW.QTDE_DIAS = 6 THEN
       SET NEW.CARGA_HORARIA_MENSAL  :=  NEW.CARGA_HORARIA_SEMANAL  * 26;
     END IF;
   
END$$;
