DROP TRIGGER CALCULAR_VALOR_TOTAL_BI;
DELIMITER $$;
CREATE TRIGGER CALCULAR_VALOR_TOTAL_BI BEFORE 
INSERT ON EMPRESTIMO_DVD_JOGO  FOR EACH ROW

BEGIN
   
   SET @VALOR_TOTAL = NEW.VALOR_DIARIA * NEW.QTDE_DIAS_EMPR;
   SET NEW.VALOR_TOTAL = @VALOR_TOTAL;

END $$;
-- --------------------------------------------------------------------------------------
DROP TRIGGER INSERT_DATE_FAB_DVD_JOGO_AI;

DELIMITER $$;
CREATE TRIGGER INSERT_DATE_FAB_DVD_JOGO_AI BEFORE
INSERT ON DVD_JOGO FOR EACH ROW

BEGIN
    
    IF NEW.DATA_FABRICACAO = '0000-00-00 00:00:00' THEN
       
        SET @DATA_FAB = NOW();
        SET NEW.DATA_FABRICACAO = @DATA_FAB;
    
    END IF;
    
END $$;
-- ---------------------------------------------------------------------------------------
DROP TRIGGER INSERT_HISTORICO_AI;
DELIMITER $$;
CREATE TRIGGER INSERT_HISTORICO_AI AFTER
INSERT ON EMPRESTIMO_DVD_JOGO FOR EACH ROW

BEGIN
   
   DECLARE LV_NOME_FUNCIONARIO VARCHAR(150);
   DECLARE LV_NOME_CLIENTE VARCHAR(150);
   DECLARE LV_NOME_DVD_JOGO  VARCHAR(150);
   
   SELECT F.NOME, 
          C.NOME,
          DJ.NOME
   INTO LV_NOME_FUNCIONARIO,
        LV_NOME_CLIENTE,
		LV_NOME_DVD_JOGO
   FROM FUNCIONARIO F, 
        CLIENTE C,
        DVD_JOGO DJ
   WHERE F.ID_FUNC = NEW.ID_FUNC
    AND C.ID_CLIENTE = NEW.ID_CLIENTE
    AND DJ.ID_DVD_JOGO = NEW.ID_DVD_JOGO ;
    
   INSERT INTO HISTORICO_EMPRESTIMO_DVD_JOGO VALUES(NEW.ID_EMP_DVD_JOGO,NEW.ID_FUNC,LV_NOME_FUNCIONARIO,NEW.ID_CLIENTE,
                                                      LV_NOME_CLIENTE,NEW.ID_DVD_JOGO,LV_NOME_DVD_JOGO,NEW.QTDE_EMPRESTADO,
                                                      NEW.QTDE_DIAS_EMPR,NEW.VALOR_DIARIA,NEW.VALOR_TOTAL,
                                                      NEW.DATA_EMPRESTIMO,NEW.DATA_CRIACAO,NEW.DATA_ATUALIZACAO, NEW.ID_USUARIO);
   
END $$;
-- -------------------------------------------------------------------------------------
DROP TRIGGER UPDATE_HISTORICO_AU;
DELIMITER $$;
CREATE TRIGGER UPDATE_HISTORICO_AU BEFORE
UPDATE ON EMPRESTIMO_DVD_JOGO FOR EACH ROW

BEGIN
   
   DECLARE LV_NOME_FUNCIONARIO VARCHAR(150);
   DECLARE LV_NOME_CLIENTE VARCHAR(150);
   DECLARE LV_NOME_DVD_JOGO  VARCHAR(150);
   
   SELECT F.NOME, 
          C.NOME,
          DJ.NOME
   INTO LV_NOME_FUNCIONARIO,
        LV_NOME_CLIENTE,
		LV_NOME_DVD_JOGO
   FROM FUNCIONARIO F, 
        CLIENTE C,
        DVD_JOGO DJ
   WHERE F.ID_FUNC = NEW.ID_FUNC
    AND C.ID_CLIENTE = NEW.ID_CLIENTE
    AND DJ.ID_DVD_JOGO = NEW.ID_DVD_JOGO ;

     
	 IF OLD.ID_FUNC <> NEW.ID_FUNC THEN
	   
	    UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET ID_FUNC = NEW.ID_FUNC
		   ,NOME_FUNCIONARIO = LV_NOME_FUNCIONARIO
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
	 
	 IF OLD.ID_CLIENTE <> NEW.ID_CLIENTE THEN
	    
		UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET ID_CLIENTE = NEW.ID_CLIENTE
		   ,NOME_CLIENTE = LV_NOME_CLIENTE
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
	 
	 IF OLD.ID_DVD_JOGO <> NEW.ID_DVD_JOGO THEN
	    
		UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET ID_DVD_JOGO = NEW.ID_DVD_JOGO
		    ,NOME_DVD_JOGO = LV_NOME_DVD_JOGO
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
		
	 END IF;
	 
	 IF OLD.QTDE_EMPRESTADO <> NEW.QTDE_EMPRESTADO THEN
	 
	    UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET QTDE_EMPRESTADO = NEW.QTDE_EMPRESTADO
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
	 
	 IF OLD.QTDE_DIAS_EMPR <> NEW.QTDE_DIAS_EMPR THEN
	    
		UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET QTDE_DIAS_EMPR = NEW.QTDE_DIAS_EMPR
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
	 
	 IF OLD.VALOR_DIARIA <> NEW.VALOR_DIARIA THEN
	    
		UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET VALOR_DIARIA = NEW.VALOR_DIARIA
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
     
     IF OLD.VALOR_DIARIA <> NEW.VALOR_DIARIA OR OLD.QTDE_DIAS_EMPR <> NEW.QTDE_DIAS_EMPR THEN
        
        SET NEW.VALOR_TOTAL = NEW.VALOR_DIARIA * NEW.QTDE_DIAS_EMPR;
	 
     END IF;
		
	 
	 IF OLD.VALOR_TOTAL <> NEW.VALOR_TOTAL THEN
	    
		UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET VALOR_TOTAL = NEW.VALOR_TOTAL
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
	 
	 IF OLD.DATA_EMPRESTIMO <> NEW.DATA_EMPRESTIMO THEN
	    
		UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET DATA_EMPRESTIMO = NEW.DATA_EMPRESTIMO
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
	 
	 IF OLD.DATA_ATUALIZACAO <> NEW.DATA_ATUALIZACAO THEN
	   
	   UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET DATA_ATUALIZACAO = NEW.DATA_ATUALIZACAO
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
	 
	 END IF;
     
     IF OLD.ID_USUARIO <> NEW.ID_USUARIO THEN
       
       UPDATE HISTORICO_EMPRESTIMO_DVD_JOGO 
		SET ID_USUARIO = NEW.ID_USUARIO
        WHERE ID_EMP_DVD_JOGO = OLD.ID_EMP_DVD_JOGO;
     
     END IF;
	 
   
END $$;